# Description: This file contains the DH parameters to be evaluated.
default:
  a: [0, 0, 0, 0, 0, 0]
  d: [0, 0, 0, 0, 0, 0]
  alpha: ["pi / 2", "pi / 2", "pi / 2", "pi / 2", "pi / 2", "pi / 2"]

ur5: &ur5_values
  a: [0, -0.425, -0.39225, 0, 0, 0]
  d: [0.089159, 0, 0, 0.10915, 0.09465, 0.0823]
  alpha: ["pi / 2", 0, 0, "pi / 2", "-pi / 2", 0]
